### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Mobhix** [Andrew2448/Andrew2448PowersuitAddons#26]
```
  Minecraft has crashed!      
  ----------------------      
```

Minecraft has stopped running because it encountered a problem; Failed to start game

A full error report has been saved to /Users/Shacker/Library/Application Support/minecraft/crash-reports/crash-2013-06-29_11.34.27-client.txt - Please include a copy of that file (Not this screen!) if you report this crash to anyone; without it, they will not be able to help fix the crash :(

--- BEGIN ERROR REPORT a0433cfe --------
Full report at:
/Users/Shacker/Library/Application Support/minecraft/crash-reports/crash-2013-06-29_11.34.27-client.txt
Please show that file to Mojang, NOT just this screen!

Generated 29.06.13 11:34

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Mac OS X (x86_64) version 10.8.4
    Java Version: 1.6.0_45, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 1864884360 bytes (1778 MB) / 2138767360 bytes (2039 MB) up to 2138767360 bytes (2039 MB)
    JVM Flags: 4 total; -Xincgc -Xmx2048M -Xms2048m -Xmx2048m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.51 FML v5.2.23.738 Minecraft Forge 7.8.1.738 Optifine OptiFine_1.5.2_HD_U_D5 16 mods loaded, 16 mods active
    mcp{7.51} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{5.2.23.738} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{7.8.1.738} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{0.8.7.1} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    ImmibisMicroblocks{55.0.5} [Immibis's Microblocks](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    mod_bspkrsCore{v2.08(1.5.2)} [bspkrsCore]([1.5.2]bspkrsCorev2.08.zip) Unloaded->Constructed->Pre-initialized->Initialized
    mod_ReiMinimap{v3.3_06 [1.5.2]} [mod_ReiMinimap]([1.5.2]ReiMinimap_v3.3_06.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ImmibisMicroblocksInstallCheck{55.0.5} [Immibis's Microblocks (Checks for incorrect installation, ignore this)](immibis-microblocks-55.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    mmmPowersuits{0.7.1-564} [MachineMuse's Modular Powersuits](ModularPowersuits-0.7.1-564.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PowersuitAddons{0.3.0-174} [Andrew2448's Modular Powersuits Addon](MPSA-0.3.0-174_MPS-555+.jar) Unloaded->Constructed->Pre-initialized->Errored
    mod_ArmorStatusHUD{v1.7(1.5.2)} [ArmorStatusHUD]([1.5.2]ArmorStatusHUDv1.7.zip) Unloaded->Constructed->Pre-initialized->Initialized
    IC2{1.116.362-lf} [IndustrialCraft 2](industrialcraft-2_1.116.362-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ChargePads{2.7.0} [Charge Pads](chargepads-1.5.2-universal-2.7.0.86.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ImmibisCore{55.1.5} [Immibis Core](immibis-core-55.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RedLogic{55.3.3} [RedLogic](redlogic-55.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PowerCraft{3.5.2} [PowerCraft](PowerCraft-Launcher_3.5.2_Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized
    LWJGL: 2.4.2
    OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-8.12.47, Intel Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Texture Pack: Shacker
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

cpw.mods.fml.common.LoaderException: java.lang.AbstractMethodError
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:147)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:213)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:448)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:733)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.AbstractMethodError
    at net.machinemuse.powersuits.powermodule.PowerModuleBase.<init>(PowerModuleBase.java:42)
    at andrew.powersuits.modules.InPlaceAssemblerModule.<init>(InPlaceAssemblerModule.java:23)
    at andrew.powersuits.common.AddonConfig.loadPowerModules(AddonConfig.java:43)
    at andrew.powersuits.common.ModularPowersuitsAddons.load(ModularPowersuitsAddons.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:192)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:172)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    ... 5 more
--- END ERROR REPORT 98ba6265 ----------

**Comment by Andrew2448** [comment]
I have not had a chance to update MPSA yet for a change in MPS last night. Use MPS-557 temporarily.

**Comment by Mobhix** [comment]
Thank You!
Great work :)
