### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by oblivion7986** [Andrew2448/Andrew2448PowersuitAddons#27]
```
  Minecraft has crashed!      
  ----------------------      
```

Minecraft has stopped running because it encountered a problem; Failed to start game

A full error report has been saved to C:\Users\Devin\AppData\Roaming.minecraft\crash-reports\crash-2013-06-30_12.54.06-client.txt - Please include a copy of that file (Not this screen!) if you report this crash to anyone; without it, they will not be able to help fix the crash :(

--- BEGIN ERROR REPORT 6a0a7759 --------
Full report at:
C:\Users\Devin\AppData\Roaming.minecraft\crash-reports\crash-2013-06-30_12.54.06-client.txt
Please show that file to Mojang, NOT just this screen!

Generated 6/30/13 12:54 PM

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_21, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 537446304 bytes (512 MB) / 663552000 bytes (632 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -Xms512m -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.51 FML v5.2.23.737 Minecraft Forge 7.8.1.737 Optifine OptiFine_1.5.2_HD_U_D5 22 mods loaded, 22 mods active
    mcp{7.51} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{5.2.23.737} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{7.8.1.737} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{0.8.7} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.5.2.28} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    mod_ReiMinimap{v3.3_06 [1.5.2]} [mod_ReiMinimap](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GuiAPI{0.15.6} [GuiAPI](GuiAPI-0.15.6-1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ConfigMod{v1.0} [Extended Mod Config](ConfigMod for MC v1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    CustomSpawner{2.2.2} [DrZhark's CustomSpawner](CustomMobSpawner 2.2.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    MoCreatures{5.2.3} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v5.2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ExtendedRenderer{v1.0} [Extended Renderer](ExtendedRenderer for MC v1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ExtrabiomesXL{3.13.4} [ExtrabiomesXL](ExtrabiomesXL-universal-1.5.2-3.13.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    iChunUtil{1.0.1} [iChunUtil](iChunUtil1.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    mmmPowersuits{0.7.0-534} [MachineMuse's Modular Powersuits](ModularPowersuits-0.7.0-534.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PowersuitAddons{0.3.0-174} [Andrew2448's Modular Powersuits Addon](MPSA-0.3.0-174_MPS-555+.jar) Unloaded->Constructed->Pre-initialized->Errored
    Mystcraft{0.10.4.00} [Mystcraft](mystcraft-uni-1.5.2-0.10.4.00.zip) Unloaded->Constructed->Pre-initialized->Initialized
    PortalGun{1.5.2} [PortalGun](PortalGun1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.5.1_1.3.6.4} [Tinkers' Construct](TConstruct_1.3.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct|CompatMineFactoryReloaded{0.1} [TConstruct Compat: MFR](TConstruct_1.3.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{3.0.5f} [Thaumcraft](Thaumcraft3.0.5f.zip) Unloaded->Constructed->Pre-initialized->Initialized
    AIBlock{v1.0} [AIBlock](Weather v1.5 Mod for MC v1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    WeatherMod{v1.5} [Weather and Tornadoes](Weather v1.5 Mod for MC v1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    LWJGL: 2.4.2
    OpenGL: Mobile Intel(R) 4 Series Express Chipset Family GL version 2.1.0 - Build 8.15.10.2086, Intel
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.machinemuse.powersuits.item.ItemComponent.addComponent(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lnet/minecraft/item/ItemStack;
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:147)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:213)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:448)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:733)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: net.machinemuse.powersuits.item.ItemComponent.addComponent(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lnet/minecraft/item/ItemStack;
    at andrew.powersuits.common.AddonComponent.populate(AddonComponent.java:13)
    at andrew.powersuits.common.ModularPowersuitsAddons.load(ModularPowersuitsAddons.java:39)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:192)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:172)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    ... 5 more
--- END ERROR REPORT dbc85e6c ----------

**Comment by Andrew2448** [comment]
Downgrade MPSA to 165, you have incompatible versions.

**Comment by oblivion7986** [comment]
Ok, Thank you :)
