### ISSUE TITLE
MPS issue

### ISSUE THREAD

**Issue by nelsonYT** [Andrew2448/Andrew2448PowersuitAddons#31]
When I press my inventory button (E), it instantly crash my game

2013-07-28 21:41:11 [Info] [STDERR] net.minecraft.util.ReportedException: Rendering entity in world
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1030)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:871)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.Minecraft.run(Minecraft.java:760)
2013-07-28 21:41:11 [Info] [STDERR] at java.lang.Thread.run(Unknown Source)
2013-07-28 21:41:11 [Info] [STDERR] Caused by: java.lang.ExceptionInInitializerError
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.utils.render.Render$$anonfun$withGlow$2$$anonfun$apply$3$$anonfun$apply$4.apply(RMonad.scala:111)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.utils.render.Render$$anonfun$withGlow$2$$anonfun$apply$3$$anonfun$apply$4.apply(RMonad.scala:110)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.utils.render.Render$$anonfun$flatMap$1.apply(RMonad.scala:24)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.utils.render.Render$$anon$1.run(RMonad.scala:30)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.utils.render.Render$$anonfun$flatMap$1.apply(RMonad.scala:24)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.utils.render.Render$$anon$1.run(RMonad.scala:30)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.utils.render.Render$$anonfun$flatMap$1.apply(RMonad.scala:24)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.utils.render.Render$$anon$1.run(RMonad.scala:30)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.powersuits.client.render.modelspec.RenderPart$$anonfun$apply$2.apply(RenderPart.scala:42)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.powersuits.client.render.modelspec.RenderPart$$anonfun$apply$2.apply(RenderPart.scala:16)
2013-07-28 21:41:11 [Info] [STDERR] at scala.Option.map(Option.scala:145)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.powersuits.client.render.modelspec.RenderPart$.apply(RenderPart.scala:16)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.powersuits.client.render.item.ArmorModel$$anonfun$render$1.apply(ArmorModel.scala:66)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.powersuits.client.render.item.ArmorModel$$anonfun$render$1.apply(ArmorModel.scala:65)
2013-07-28 21:41:11 [Info] [STDERR] at scala.collection.Iterator$class.foreach(Iterator.scala:727)
2013-07-28 21:41:11 [Info] [STDERR] at scala.collection.AbstractIterator.foreach(Iterator.scala:1156)
2013-07-28 21:41:11 [Info] [STDERR] at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
2013-07-28 21:41:11 [Info] [STDERR] at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.powersuits.client.render.item.ArmorModel.func_78088_a(ArmorModel.scala:65)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.renderer.entity.RenderLiving.func_77031_a(RenderLiving.java:137)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.renderer.entity.RenderPlayer.func_77101_a(RenderPlayer.java:187)
2013-07-28 21:41:11 [Info] [STDERR] at gregtechmod.common.render.GT_Renderer.func_77101_a(GT_Renderer.java:27)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:563)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.renderer.entity.RenderManager.func_78719_a(RenderManager.java:310)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.gui.inventory.GuiInventory.func_74223_a(SourceFile:89)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.gui.inventory.GuiInventory.func_74185_a(SourceFile:61)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:124)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(SourceFile:31)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:48)
2013-07-28 21:41:11 [Info] [STDERR] at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1021)
2013-07-28 21:41:11 [Info] [STDERR] ... 3 more
2013-07-28 21:41:11 [Info] [STDERR] Caused by: java.lang.RuntimeException: Framebuffers not supported!
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.utils.render.TextureBuffer.<init>(TextureBuffer.scala:16)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.utils.render.GlowBuffer$.<init>(GlowBuffer.scala:19)
2013-07-28 21:41:11 [Info] [STDERR] at net.machinemuse.utils.render.GlowBuffer$.<clinit>(GlowBuffer.scala)
2013-07-28 21:41:11 [Info] [STDERR] ... 33 more

**Comment by Andrew2448** [comment]
This is not an addons bug...
