### ISSUE TITLE
Crash from solar generator?

### ISSUE THREAD

**Issue by ntwitch** [Andrew2448/Andrew2448PowersuitAddons#6]
Full Log: http://pastebin.com/8mDuNchB

This has only happened once so far, I've had the solar generator installed for a while with no issues. Not sure how to recreate this. Might be hard to track down, but I thought I'd report it.

EDIT: although it mentions biomes I'd like to note that I don't have any biome modifying mods in the overworld (twilight forest is installed, but I haven't even gone there)

2013-05-02 09:44:58 [INFO] [STDERR] net.minecraft.util.ReportedException: Ticking entity
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.world.World.func_72939_s(World.java:2159)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1852)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:834)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.client.Minecraft.run(Minecraft.java:759)
2013-05-02 09:44:58 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2013-05-02 09:44:58 [INFO] [STDERR] Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.world.biome.WorldChunkManager.func_76934_b(WorldChunkManager.java:125)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.world.biome.BiomeCacheBlock.<init>(SourceFile:27)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:58)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.world.biome.BiomeCache.func_76837_b(SourceFile:67)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.world.biome.WorldChunkManager.func_76935_a(WorldChunkManager.java:67)
2013-05-02 09:44:58 [INFO] [STDERR]     at andrew.powersuits.modules.SolarGeneratorModule.onPlayerTickActive(SolarGeneratorModule.java:59)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.machinemuse.powersuits.tick.PlayerTickHandler.handle(PlayerTickHandler.java:67)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.machinemuse.powersuits.tick.PlayerTickHandler.tickStart(PlayerTickHandler.java:41)
2013-05-02 09:44:58 [INFO] [STDERR]     at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)
2013-05-02 09:44:58 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)
2013-05-02 09:44:58 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:383)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:279)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:45)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.world.World.func_72866_a(World.java:2336)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.world.World.func_72870_g(World.java:2298)
2013-05-02 09:44:58 [INFO] [STDERR]     at net.minecraft.world.World.func_72939_s(World.java:2144)
2013-05-02 09:44:58 [INFO] [STDERR]     ... 4 more

**Comment by Andrew2448** [comment]
Is this on world join? On startup? Randomly during gameplay?

**Comment by ntwitch** [comment]
Ah, sorry. Randomly in gameplay. Still hasn't happened again, but I got a similar crash that only included vanilla classes (including the same biome and chunk manager classes as in the above error) so maybe it wasn't your mod after all. Possibly a vanilla bug or mod interaction.

**Comment by Andrew2448** [comment]
Ok, I'll close this for now then. Feel free to reopen if you can pin it down to my mod.
